spring:
  datasource:
    druid: 
      url: jdbc:mysql://'{cipher}AQAqGdQmYZTefl5KrUwlpoanuuRNzYAJ0sKDO/Oks6mLk7sAhmq14gNRLrc5h7KOf9OivLTfIWwRin1a7k5lVp621a7FDvY+aK2pn1/2Z9lNYw7wJTZSknqhBw4OzfuJmsuZj/WJjnLdoeWlRT3S85nD0XREd+WknE6naaNn7DrkhCSgtTtPvXx8rZIm70SdBsF5x2vsFyMoBfrS36TkVoIaA1/xvA6M824kjCUwrBt18yksae12BCdFLAL7CD4KUJCu3LeNuj1TA5s9AygqawvH7bBXWrGGr/PzxLq6UNvpd+Yeo73MiLIPIqQs0ZAYfQ7Q+4ADeTongZt7Y+ewVbLZvEdRgenZiIBhd4bPkjcz/SmfvYvLCrBuuBr1mJKsJYE=':3306/'{cipher}AQBlAGnRGVTUve5srfOMwHf9tQc8MRJqFQKhRekA/blnFOz+1aeVX+TFLQjkAbbkZIR8X1uFn0/qdIHU8Cwcs7xTU8s9SGGf3wRqyPnsds9lqrNsczhdIVi8ZQNrwhuFHbiCUrsPP9DWjnSN29RUcKvUWJHMuJF/TvkC4zu7AaVvDojHMx4DlaSNuak9lnlN6Y2cNqBV499w7ttC9hCVzpjIah2/xp15SSpeQPPtU9YIfaZgNLYH6AlK3opN+VaRQK+gGv2fQOkyb70wVg7/STcVf4FdqxEKni1TxHRNlUNjpARV93t+LHY45mj54oec0eT+Ph61L9CABrrc2/L+2OZFPcfGxxNDWY7pDH8s6eGB3VJCf84fha14gePGIVtzePM='?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      driverClassName: com.mysql.jdbc.Driver
      username: '{cipher}AQB0rrTvTZOg7pXi75ddfFkwsB1/bg1VGmgHli07/ZGVB+nV6OwvsjmKz1LqsqD0Dkbwn2A96hS8lN5bQfKDRt494Uw1Shfo9hB7apXSQBTXN4jXbUojzBNkWH6nI+gkbvazfw4dloKj+dR7DREid9EQPQvixwEsaMiwbANYRep/mGRylzWsorEubYTVMYrDRzwmNBUYEx9du+jfYr8TH+YUmZNHiRgQSuUEAnQFrCCR0lCP5nU2W1c6uygduz1hvam3RWaucJbpmfwgSQ5pzsTJjECiwKk8XWwz9qpmfdQfdpPtwVYuKUHO8RzntIZO3jdPbfsYERFydGUq/hnAuTqbic0KN6r0Ic30DA/QO+jTfKQGN0OlvZ0Aw5HMnMZ6vQo='
      password: '{cipher}AQB0rrTvTZOg7pXi75ddfFkwsB1/bg1VGmgHli07/ZGVB+nV6OwvsjmKz1LqsqD0Dkbwn2A96hS8lN5bQfKDRt494Uw1Shfo9hB7apXSQBTXN4jXbUojzBNkWH6nI+gkbvazfw4dloKj+dR7DREid9EQPQvixwEsaMiwbANYRep/mGRylzWsorEubYTVMYrDRzwmNBUYEx9du+jfYr8TH+YUmZNHiRgQSuUEAnQFrCCR0lCP5nU2W1c6uygduz1hvam3RWaucJbpmfwgSQ5pzsTJjECiwKk8XWwz9qpmfdQfdpPtwVYuKUHO8RzntIZO3jdPbfsYERFydGUq/hnAuTqbic0KN6r0Ic30DA/QO+jTfKQGN0OlvZ0Aw5HMnMZ6vQo='
      filters: stat,slf4j,wall
      initialSize: 10
      maxActive: 100
      maxWait: 60000
      minIdle: 10
      logAbandoned: true
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      removeAbandoned: true
      validationQuery: SELECT X FROM DUAL
      removeAbandonedTimeout: 1800
      poolPreparedStatements: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxPoolPreparedStatementPerConnectionSize: 20
  logging: 
     config: classpath:logback-spring.xml
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    #password: 
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

mybatis:   
  mapperLocations: classpath:config/mybatis/*/*.xml
  typeAliasesPackage: com.fs.entity
  check-config-location: true
  config-location: classpath:mybatis-config.xml