spring:
  datasource:
    druid: 
      url: jdbc:mysql://172.29.139.15:3306/wyltest2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root
      filters: stat,slf4j,wall
      initialSize: 10
      maxActive: 100
      maxWait: 60000
      minIdle: 10
      logAbandoned: true
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      removeAbandoned: true
      validationQuery: SELECT X FROM DUAL
      removeAbandonedTimeout: 1800
      poolPreparedStatements: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxPoolPreparedStatementPerConnectionSize: 20
  logging: 
     config: classpath:logback-spring.xml
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    #password: 
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

mybatis:   
  mapperLocations: classpath:config/mybatis/*/*.xml
  typeAliasesPackage: com.fs.entity
  check-config-location: true
  config-location: classpath:mybatis-config.xml

hi: '{cipher}AQB1/CphTUFELezN2d/NBpphmCyoJrAo20D/IcOlkS1+gO9GaIf+GRHbEJFGn20121H8jyChNkEKbe7wdI1Hsj74qqjoFwPihPAoFpG5po4rAT/qrwAQWvyI7GwyBU05QzCUuzD0IV4fReMiCS1/bYtuRdKUQhb7FYOyvo3sVxsqIT0zjJOWI5VSqsLqFXbPovVnQA02ZSHu5P4vz83H0dvFnJLOuhpeVr+UwHtHOdZ05CUNL+OMBfBFL/jP6bPWcrXmC1xIx0URVKRQlrkTRtRlMaLxEdWvEu7PCzstFOHwH1C7z+qrI3ZilxDqb8YgcuaFV2UPFFM16GtvA1rbep+XuoZKvIa7uJLYKTBBnM83a3fwaiIDc1/RD4fJ2iLbPPQ='