spring:
  datasource:
    druid: 
      url: jdbc:mysql://172.29.139.15:3306/suncard?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root
      filters: stat,slf4j,wall
      initialSize: 10
      maxActive: 100
      maxWait: 60000
      minIdle: 10
      logAbandoned: true
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      removeAbandoned: true
      validationQuery: SELECT 'x'
      removeAbandonedTimeout: 1800
      poolPreparedStatements: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxPoolPreparedStatementPerConnectionSize: 20