server:
  session:
    timeout: 20
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    druid: 
      url: jdbc:mysql://172.29.139.15:3306/suncard?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root
      filters: stat,slf4j,wall
      initialSize: 10
      maxActive: 100
      maxWait: 60000
      minIdle: 10
      logAbandoned: true
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      removeAbandoned: true
      validationQuery: SELECT 'x'
      removeAbandonedTimeout: 1800
      poolPreparedStatements: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxPoolPreparedStatementPerConnectionSize: 20
  logging: 
     config: classpath:logback.xml
  redis:
    host: 172.29.140.87
    port: 6379
#Redis数据库索引（默认为0）
    database: 0
#Redis服务器连接密码（默认为空）
    password: 
    pool:
#连接池中的最大空闲连接
      max-idle: 8
      min-idle: 0
#连接池最大连接数（使用负值表示没有限制）
      max-active: 8
#连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
#指定在一个 client 空闲多少秒之后关闭连接（0 就是不管它）
      timeout: 0